
services:
  mongo:
    image: mongo:latest
    container_name: rag-db
    ports:
      - "27017:27017"
    volumes:
      - rag-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: AI-model
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 3
    

  app:
    build: .
    container_name: rag-one
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  rag-data:
